repositories:
  - name: bitnami
    url: https://raw.githubusercontent.com/bitnami/charts/archive-full-index/bitnami
  - name: elastic
    url: https://helm.elastic.co
  - name: hashicorp
    url: https://helm.releases.hashicorp.com
  - name: provectus
    url: https://provectus.github.io/kafka-ui-charts

releases:
  - name: postgresql
    namespace: postgresql
    chart: bitnami/postgresql
    values:
      - ./deps/postgresql/values.yaml

  - name: redis
    namespace: redis
    chart: bitnami/redis
    values:
      - ./deps/redis/values.yaml

  - name: kafka
    namespace: kafka
    createNamespace: true
    chart: bitnami/kafka
    values:
      - ./deps/kafka/values.yaml

  - name: elastic
    namespace: elastic
    chart: elastic/elasticsearch
    values:
      - ./deps/elastic/values.yaml

  - name: kafka-ui
    namespace: kafka-ui
    chart: provectus/kafka-ui
    values:
      - ./deps/kafka-ui/values.yaml

  - name: link-collector
    namespace: service
    createNamespace: true
    chart: ./collector
    values:
      - ./collector/values.yaml
