repositories:
  - name: itboon-kafka
    url: https://helm-charts.itboon.top/kafka
  - name: provectus
    url: https://provectus.github.io/kafka-ui-charts

releases:
  - name: kafka
    namespace: default
    chart: itboon-kafka/kafka
    values:
    - ./deps/kafka/values.yaml

  - name: kafka-ui
    namespace: default
    chart: provectus/kafka-ui
    values:
    - ./deps/kafka-ui/values.yaml

  - name: link-collector
    namespace: default
    chart: ./collector
    values:
    - ./collector/values.yaml
