image:
  repository: bitnamilegacy/kafka
  tag: latest
zookeeper:
  replicaCount: 1
  persistence:
    enabled: false

replicaCount: 1

auth:
  clientProtocol: sasl
  sasl:
    mechanisms: plain
    jaas:
      enabled: true

createTopics:
  enabled: true
  bootstrapServer: ""
  topics:
    - name: links
      partitions: 3
      replicationFactor: 1