replicaCount: 1

zookeeper:
  enabled: true

listeners:
  client:
    protocol: PLAINTEXT

externalAccess:
  enabled: false  # если Kafka используется только внутри кластера

persistence:
  enabled: true
  size: 8Gi

resources:
  requests:
    cpu: 100m
    memory: 512Mi
  limits:
    cpu: 500m
    memory: 1Gi

auth:
  clientProtocol: plaintext